#!/usr/bin/env python3
"""
docs.py — generate a per-file markdown breakdown of topology.toml and its
sidecar TOML files (name/hostname of each entry, with a GitHub line-number
link back to the raw TOML), and write it into $TOPOLOGIES_HOME/README.md
between marker comments so re-running stays idempotent.

Invoked via: /topology docs
"""

import os
import re
import sys

from .sync import get_topology_path, list_sidecars

START_MARKER = '<!-- topology-docs:start -->'
END_MARKER = '<!-- topology-docs:end -->'

_ARRAY_RE = re.compile(r'^\[\[(\w+)\]\]$')
_TABLE_RE = re.compile(r'^\[(\w+)\]$')
_KV_RE = re.compile(r'^(\w+)\s*=\s*(.+)$')


def _clean_value(raw: str, limit: int = 60) -> str:
    raw = raw.strip()
    if raw.startswith('"') and raw.endswith('"') and len(raw) >= 2:
        raw = raw[1:-1]
    elif raw.startswith("'''"):
        raw = raw[3:].split('\n', 1)[0].strip() or '(multi-line)'
    return raw if len(raw) <= limit else raw[: limit - 1] + '…'


def index_entries(path: str) -> list[dict]:
    """Return one {'section', 'line', 'label'} entry per top-level [[x]]/[x] header, in file order."""
    entries: list[dict] = []
    current: dict | None = None

    with open(path) as f:
        lines = f.readlines()

    for i, line in enumerate(lines, start=1):
        stripped = line.strip()
        array_m = _ARRAY_RE.match(stripped)
        table_m = _TABLE_RE.match(stripped)
        if array_m or table_m:
            if current is not None:
                entries.append(current)
            current = {'section': (array_m or table_m).group(1), 'line': i, 'label': None}
            continue
        if current is not None and current['label'] is None:
            kv_m = _KV_RE.match(stripped)
            if kv_m:
                current['label'] = _clean_value(kv_m.group(2))

    if current is not None:
        entries.append(current)

    return entries


def render_file_section(path: str) -> str:
    basename = os.path.basename(path)
    entries = index_entries(path)

    lines = [f'### `{basename}`', '']

    if not entries:
        lines.append('_(no entries)_')
        lines.append('')
        return '\n'.join(lines)

    grouped: dict[str, list[dict]] = {}
    for entry in entries:
        grouped.setdefault(entry['section'], []).append(entry)

    for section, section_entries in grouped.items():
        lines.append(f'**{section}** ({len(section_entries)})')
        lines.append('')
        for entry in section_entries:
            label = entry['label'] or '(untitled)'
            lines.append(f'- `{label}` — [line {entry["line"]}]({basename}#L{entry["line"]})')
        lines.append('')

    return '\n'.join(lines).rstrip() + '\n'


def render_docs(files: list[str]) -> str:
    parts = [
        START_MARKER, '',
        '## File contents', '',
        '_Generated by `topology docs` — do not edit by hand._', '',
    ]
    for path in files:
        parts.append(render_file_section(path))
    parts.append(END_MARKER)
    return '\n'.join(parts).rstrip() + '\n'


def update_readme(readme_path: str, generated: str) -> None:
    content = ''
    if os.path.exists(readme_path):
        with open(readme_path) as f:
            content = f.read()

    if START_MARKER in content and END_MARKER in content:
        start = content.index(START_MARKER)
        end = content.index(END_MARKER) + len(END_MARKER)
        content = content[:start] + generated + content[end:]
    elif content:
        content = content.rstrip('\n') + '\n\n' + generated
    else:
        content = generated

    with open(readme_path, 'w') as f:
        f.write(content)


def main() -> None:
    topology_path = get_topology_path()
    if not os.path.exists(topology_path):
        print(f'Topology not found: {topology_path}', file=sys.stderr)
        sys.exit(1)

    topologies_home = os.path.dirname(topology_path)
    files = [topology_path] + list_sidecars(topologies_home)
    generated = render_docs(files)

    readme_path = os.path.join(topologies_home, 'README.md')
    update_readme(readme_path, generated)

    print(f'Updated {readme_path}')


if __name__ == '__main__':
    main()
